version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm ci
  build:
    commands:
      - echo "Build phase complete"

artifacts:
  files:
    - '**/*'
  discard-paths: no
